/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddProjectRouteImport } from './routes/add-project'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as SpecsIndexRouteImport } from './routes/specs.index'
import { Route as SpecsIdRouteImport } from './routes/specs.$id'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as TestsIdRouteImport } from './routes/tests.$id'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as ProjectsIdSpecsRouteImport } from './routes/projects.$id.specs'
import { Route as ProjectsIdTestScenariosRouteImport } from './routes/projects.$id.test-scenarios'
import { Route as ProjectsIdSpecsIndexRouteImport } from './routes/projects.$id.specs.index'
import { Route as ProjectsIdSpecsIdRouteImport } from './routes/projects.$id.specs.$id'
import { Route as ProjectsIdTestScenariosIndexRouteImport } from './routes/projects.$id.test-scenarios.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddProjectRoute = AddProjectRouteImport.update({
  id: '/add-project',
  path: '/add-project',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsIndexRoute = SpecsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecsRoute,
} as any)
const SpecsIdRoute = SpecsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpecsRoute,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsRoute,
} as any)
const TestsIdRoute = TestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TestsRoute,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdSpecsRoute = ProjectsIdSpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdTestScenariosRoute = ProjectsIdTestScenariosRouteImport.update({
  id: '/test-scenarios',
  path: '/test-scenarios',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdSpecsIndexRoute = ProjectsIdSpecsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdSpecsRoute,
} as any)
const ProjectsIdSpecsIdRoute = ProjectsIdSpecsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsIdSpecsRoute,
} as any)
const ProjectsIdTestScenariosIndexRoute =
  ProjectsIdTestScenariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsIdTestScenariosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-project': typeof AddProjectRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/specs': typeof SpecsRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/runs/$id': typeof RunsIdRoute
  '/specs/$id': typeof SpecsIdRoute
  '/tests/$id': typeof TestsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/projects/$id/specs': typeof ProjectsIdSpecsRouteWithChildren
  '/projects/$id/test-scenarios': typeof ProjectsIdTestScenariosRouteWithChildren
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/specs/$id': typeof ProjectsIdSpecsIdRoute
  '/projects/$id/specs/': typeof ProjectsIdSpecsIndexRoute
  '/projects/$id/test-scenarios/': typeof ProjectsIdTestScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-project': typeof AddProjectRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/runs/$id': typeof RunsIdRoute
  '/specs/$id': typeof SpecsIdRoute
  '/tests/$id': typeof TestsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/specs': typeof SpecsIndexRoute
  '/tests': typeof TestsIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/projects/$id/specs/$id': typeof ProjectsIdSpecsIdRoute
  '/projects/$id/specs': typeof ProjectsIdSpecsIndexRoute
  '/projects/$id/test-scenarios': typeof ProjectsIdTestScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-project': typeof AddProjectRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/specs': typeof SpecsRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/runs/$id': typeof RunsIdRoute
  '/specs/$id': typeof SpecsIdRoute
  '/tests/$id': typeof TestsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/projects/$id/specs': typeof ProjectsIdSpecsRouteWithChildren
  '/projects/$id/test-scenarios': typeof ProjectsIdTestScenariosRouteWithChildren
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/specs/$id': typeof ProjectsIdSpecsIdRoute
  '/projects/$id/specs/': typeof ProjectsIdSpecsIndexRoute
  '/projects/$id/test-scenarios/': typeof ProjectsIdTestScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-project'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/projects'
    | '/specs'
    | '/tests'
    | '/projects/$id'
    | '/runs/$id'
    | '/specs/$id'
    | '/tests/$id'
    | '/projects/'
    | '/specs/'
    | '/tests/'
    | '/projects/$id/specs'
    | '/projects/$id/test-scenarios'
    | '/projects/$id/'
    | '/projects/$id/specs/$id'
    | '/projects/$id/specs/'
    | '/projects/$id/test-scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-project'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/runs/$id'
    | '/specs/$id'
    | '/tests/$id'
    | '/projects'
    | '/specs'
    | '/tests'
    | '/projects/$id'
    | '/projects/$id/specs/$id'
    | '/projects/$id/specs'
    | '/projects/$id/test-scenarios'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-project'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/projects'
    | '/specs'
    | '/tests'
    | '/projects/$id'
    | '/runs/$id'
    | '/specs/$id'
    | '/tests/$id'
    | '/projects/'
    | '/specs/'
    | '/tests/'
    | '/projects/$id/specs'
    | '/projects/$id/test-scenarios'
    | '/projects/$id/'
    | '/projects/$id/specs/$id'
    | '/projects/$id/specs/'
    | '/projects/$id/test-scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddProjectRoute: typeof AddProjectRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SpecsRoute: typeof SpecsRouteWithChildren
  TestsRoute: typeof TestsRouteWithChildren
  RunsIdRoute: typeof RunsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-project': {
      id: '/add-project'
      path: '/add-project'
      fullPath: '/add-project'
      preLoaderRoute: typeof AddProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs/': {
      id: '/specs/'
      path: '/'
      fullPath: '/specs/'
      preLoaderRoute: typeof SpecsIndexRouteImport
      parentRoute: typeof SpecsRoute
    }
    '/specs/$id': {
      id: '/specs/$id'
      path: '/$id'
      fullPath: '/specs/$id'
      preLoaderRoute: typeof SpecsIdRouteImport
      parentRoute: typeof SpecsRoute
    }
    '/tests/': {
      id: '/tests/'
      path: '/'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/$id': {
      id: '/tests/$id'
      path: '/$id'
      fullPath: '/tests/$id'
      preLoaderRoute: typeof TestsIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/specs': {
      id: '/projects/$id/specs'
      path: '/specs'
      fullPath: '/projects/$id/specs'
      preLoaderRoute: typeof ProjectsIdSpecsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/test-scenarios': {
      id: '/projects/$id/test-scenarios'
      path: '/test-scenarios'
      fullPath: '/projects/$id/test-scenarios'
      preLoaderRoute: typeof ProjectsIdTestScenariosRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/specs/': {
      id: '/projects/$id/specs/'
      path: '/'
      fullPath: '/projects/$id/specs/'
      preLoaderRoute: typeof ProjectsIdSpecsIndexRouteImport
      parentRoute: typeof ProjectsIdSpecsRoute
    }
    '/projects/$id/specs/$id': {
      id: '/projects/$id/specs/$id'
      path: '/$id'
      fullPath: '/projects/$id/specs/$id'
      preLoaderRoute: typeof ProjectsIdSpecsIdRouteImport
      parentRoute: typeof ProjectsIdSpecsRoute
    }
    '/projects/$id/test-scenarios/': {
      id: '/projects/$id/test-scenarios/'
      path: '/'
      fullPath: '/projects/$id/test-scenarios/'
      preLoaderRoute: typeof ProjectsIdTestScenariosIndexRouteImport
      parentRoute: typeof ProjectsIdTestScenariosRoute
    }
  }
}

interface ProjectsIdSpecsRouteChildren {
  ProjectsIdSpecsIdRoute: typeof ProjectsIdSpecsIdRoute
  ProjectsIdSpecsIndexRoute: typeof ProjectsIdSpecsIndexRoute
}

const ProjectsIdSpecsRouteChildren: ProjectsIdSpecsRouteChildren = {
  ProjectsIdSpecsIdRoute: ProjectsIdSpecsIdRoute,
  ProjectsIdSpecsIndexRoute: ProjectsIdSpecsIndexRoute,
}

const ProjectsIdSpecsRouteWithChildren = ProjectsIdSpecsRoute._addFileChildren(
  ProjectsIdSpecsRouteChildren,
)

interface ProjectsIdTestScenariosRouteChildren {
  ProjectsIdTestScenariosIndexRoute: typeof ProjectsIdTestScenariosIndexRoute
}

const ProjectsIdTestScenariosRouteChildren: ProjectsIdTestScenariosRouteChildren =
  {
    ProjectsIdTestScenariosIndexRoute: ProjectsIdTestScenariosIndexRoute,
  }

const ProjectsIdTestScenariosRouteWithChildren =
  ProjectsIdTestScenariosRoute._addFileChildren(
    ProjectsIdTestScenariosRouteChildren,
  )

interface ProjectsIdRouteChildren {
  ProjectsIdSpecsRoute: typeof ProjectsIdSpecsRouteWithChildren
  ProjectsIdTestScenariosRoute: typeof ProjectsIdTestScenariosRouteWithChildren
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdSpecsRoute: ProjectsIdSpecsRouteWithChildren,
  ProjectsIdTestScenariosRoute: ProjectsIdTestScenariosRouteWithChildren,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SpecsRouteChildren {
  SpecsIdRoute: typeof SpecsIdRoute
  SpecsIndexRoute: typeof SpecsIndexRoute
}

const SpecsRouteChildren: SpecsRouteChildren = {
  SpecsIdRoute: SpecsIdRoute,
  SpecsIndexRoute: SpecsIndexRoute,
}

const SpecsRouteWithChildren = SpecsRoute._addFileChildren(SpecsRouteChildren)

interface TestsRouteChildren {
  TestsIdRoute: typeof TestsIdRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsIdRoute: TestsIdRoute,
  TestsIndexRoute: TestsIndexRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddProjectRoute: AddProjectRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SpecsRoute: SpecsRouteWithChildren,
  TestsRoute: TestsRouteWithChildren,
  RunsIdRoute: RunsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
